/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Blob = Uint8Array;
export interface NinjaTechnique {
    name: string;
    effect?: TechniqueEffect;
    power: bigint;
}
export type ElementalMastery = {
    __kind__: "ice";
    ice: string;
} | {
    __kind__: "magnetizer";
    magnetizer: string;
} | {
    __kind__: "magmarizer";
    magmarizer: string;
} | {
    __kind__: "dark";
    dark: string;
} | {
    __kind__: "dawn";
    dawn: string;
} | {
    __kind__: "dusk";
    dusk: string;
} | {
    __kind__: "fire";
    fire: string;
} | {
    __kind__: "wind";
    wind: string;
} | {
    __kind__: "metalCoat";
    metalCoat: string;
} | {
    __kind__: "upgrade";
    upgrade: string;
} | {
    __kind__: "earth";
    earth: string;
} | {
    __kind__: "kingRock";
    kingRock: string;
} | {
    __kind__: "skyScale";
    skyScale: string;
} | {
    __kind__: "protector";
    protector: string;
} | {
    __kind__: "hydration";
    hydration: string;
} | {
    __kind__: "moonStone";
    moonStone: string;
} | {
    __kind__: "water";
    water: string;
} | {
    __kind__: "prismScale";
    prismScale: string;
} | {
    __kind__: "lightning";
    lightning: string;
} | {
    __kind__: "ovalStone";
    ovalStone: string;
} | {
    __kind__: "shineStone";
    shineStone: string;
} | {
    __kind__: "seaScale";
    seaScale: string;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MonsterUltimate {
    shenanigans: bigint;
    speed: bigint;
    stage: string;
    monsterId: bigint;
    defense: bigint;
    monsterName: string;
    agility: bigint;
    attack: bigint;
    reactions: bigint;
    images: Array<MonsterImage>;
}
export interface Monster {
    battleTechniques: Array<NinjaTechnique>;
    level: bigint;
    baseSpeed: bigint;
    monsterName: string;
    baseAttack: bigint;
    masteryElement?: ElementalMastery;
    baseDefense: bigint;
    images: Array<MonsterImage>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MonsterImage {
    isAnimated: boolean;
    imagePath: string;
    imageUrl: string;
    isRawImage: boolean;
    image: Blob;
}
export interface UserProfile {
    victories: bigint;
    ninjaName: string;
    avatarUrl?: string;
    dojoSeals: bigint;
    clanName: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum TechniqueEffect {
    boostSpeed = "boostSpeed",
    paralyzeOpponent = "paralyzeOpponent",
    confuseOpponent = "confuseOpponent",
    boostDefense = "boostDefense",
    boostAttack = "boostAttack"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getDojoSeals(): Promise<Array<string>>;
    getLog(): Promise<Array<string>>;
    getMonsterDXData(monster: string): Promise<Monster | null>;
    getMonsters(): Promise<Array<Monster>>;
    getOpponent(type: string): Promise<string>;
    getUltimateMonsters(): Promise<Array<MonsterUltimate>>;
    getUserProfile(user: Principal): Promise<UserProfile>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { ElementalMastery as _ElementalMastery, Monster as _Monster, MonsterImage as _MonsterImage, NinjaTechnique as _NinjaTechnique, TechniqueEffect as _TechniqueEffect, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDojoSeals(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDojoSeals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDojoSeals();
            return result;
        }
    }
    async getLog(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLog();
            return result;
        }
    }
    async getMonsterDXData(arg0: string): Promise<Monster | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonsterDXData(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonsterDXData(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonsters(): Promise<Array<Monster>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonsters();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonsters();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpponent(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpponent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpponent(arg0);
            return result;
        }
    }
    async getUltimateMonsters(): Promise<Array<MonsterUltimate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUltimateMonsters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUltimateMonsters();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ElementalMastery_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ElementalMastery): ElementalMastery {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Monster_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Monster): Monster {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_NinjaTechnique_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NinjaTechnique): NinjaTechnique {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TechniqueEffect_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TechniqueEffect): TechniqueEffect {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Monster]): Monster | null {
    return value.length === 0 ? null : from_candid_Monster_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TechniqueEffect]): TechniqueEffect | null {
    return value.length === 0 ? null : from_candid_TechniqueEffect_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ElementalMastery]): ElementalMastery | null {
    return value.length === 0 ? null : from_candid_ElementalMastery_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    victories: bigint;
    ninjaName: string;
    avatarUrl: [] | [string];
    dojoSeals: bigint;
    clanName: string;
}): {
    victories: bigint;
    ninjaName: string;
    avatarUrl?: string;
    dojoSeals: bigint;
    clanName: string;
} {
    return {
        victories: value.victories,
        ninjaName: value.ninjaName,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.avatarUrl)),
        dojoSeals: value.dojoSeals,
        clanName: value.clanName
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    battleTechniques: Array<_NinjaTechnique>;
    level: bigint;
    baseSpeed: bigint;
    monsterName: string;
    baseAttack: bigint;
    masteryElement: [] | [_ElementalMastery];
    baseDefense: bigint;
    images: Array<_MonsterImage>;
}): {
    battleTechniques: Array<NinjaTechnique>;
    level: bigint;
    baseSpeed: bigint;
    monsterName: string;
    baseAttack: bigint;
    masteryElement?: ElementalMastery;
    baseDefense: bigint;
    images: Array<MonsterImage>;
} {
    return {
        battleTechniques: from_candid_vec_n18(_uploadFile, _downloadFile, value.battleTechniques),
        level: value.level,
        baseSpeed: value.baseSpeed,
        monsterName: value.monsterName,
        baseAttack: value.baseAttack,
        masteryElement: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.masteryElement)),
        baseDefense: value.baseDefense,
        images: value.images
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    effect: [] | [_TechniqueEffect];
    power: bigint;
}): {
    name: string;
    effect?: TechniqueEffect;
    power: bigint;
} {
    return {
        name: value.name,
        effect: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.effect)),
        power: value.power
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    boostSpeed: null;
} | {
    paralyzeOpponent: null;
} | {
    confuseOpponent: null;
} | {
    boostDefense: null;
} | {
    boostAttack: null;
}): TechniqueEffect {
    return "boostSpeed" in value ? TechniqueEffect.boostSpeed : "paralyzeOpponent" in value ? TechniqueEffect.paralyzeOpponent : "confuseOpponent" in value ? TechniqueEffect.confuseOpponent : "boostDefense" in value ? TechniqueEffect.boostDefense : "boostAttack" in value ? TechniqueEffect.boostAttack : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ice: string;
} | {
    magnetizer: string;
} | {
    magmarizer: string;
} | {
    dark: string;
} | {
    dawn: string;
} | {
    dusk: string;
} | {
    fire: string;
} | {
    wind: string;
} | {
    metalCoat: string;
} | {
    upgrade: string;
} | {
    earth: string;
} | {
    kingRock: string;
} | {
    skyScale: string;
} | {
    protector: string;
} | {
    hydration: string;
} | {
    moonStone: string;
} | {
    water: string;
} | {
    prismScale: string;
} | {
    lightning: string;
} | {
    ovalStone: string;
} | {
    shineStone: string;
} | {
    seaScale: string;
}): {
    __kind__: "ice";
    ice: string;
} | {
    __kind__: "magnetizer";
    magnetizer: string;
} | {
    __kind__: "magmarizer";
    magmarizer: string;
} | {
    __kind__: "dark";
    dark: string;
} | {
    __kind__: "dawn";
    dawn: string;
} | {
    __kind__: "dusk";
    dusk: string;
} | {
    __kind__: "fire";
    fire: string;
} | {
    __kind__: "wind";
    wind: string;
} | {
    __kind__: "metalCoat";
    metalCoat: string;
} | {
    __kind__: "upgrade";
    upgrade: string;
} | {
    __kind__: "earth";
    earth: string;
} | {
    __kind__: "kingRock";
    kingRock: string;
} | {
    __kind__: "skyScale";
    skyScale: string;
} | {
    __kind__: "protector";
    protector: string;
} | {
    __kind__: "hydration";
    hydration: string;
} | {
    __kind__: "moonStone";
    moonStone: string;
} | {
    __kind__: "water";
    water: string;
} | {
    __kind__: "prismScale";
    prismScale: string;
} | {
    __kind__: "lightning";
    lightning: string;
} | {
    __kind__: "ovalStone";
    ovalStone: string;
} | {
    __kind__: "shineStone";
    shineStone: string;
} | {
    __kind__: "seaScale";
    seaScale: string;
} {
    return "ice" in value ? {
        __kind__: "ice",
        ice: value.ice
    } : "magnetizer" in value ? {
        __kind__: "magnetizer",
        magnetizer: value.magnetizer
    } : "magmarizer" in value ? {
        __kind__: "magmarizer",
        magmarizer: value.magmarizer
    } : "dark" in value ? {
        __kind__: "dark",
        dark: value.dark
    } : "dawn" in value ? {
        __kind__: "dawn",
        dawn: value.dawn
    } : "dusk" in value ? {
        __kind__: "dusk",
        dusk: value.dusk
    } : "fire" in value ? {
        __kind__: "fire",
        fire: value.fire
    } : "wind" in value ? {
        __kind__: "wind",
        wind: value.wind
    } : "metalCoat" in value ? {
        __kind__: "metalCoat",
        metalCoat: value.metalCoat
    } : "upgrade" in value ? {
        __kind__: "upgrade",
        upgrade: value.upgrade
    } : "earth" in value ? {
        __kind__: "earth",
        earth: value.earth
    } : "kingRock" in value ? {
        __kind__: "kingRock",
        kingRock: value.kingRock
    } : "skyScale" in value ? {
        __kind__: "skyScale",
        skyScale: value.skyScale
    } : "protector" in value ? {
        __kind__: "protector",
        protector: value.protector
    } : "hydration" in value ? {
        __kind__: "hydration",
        hydration: value.hydration
    } : "moonStone" in value ? {
        __kind__: "moonStone",
        moonStone: value.moonStone
    } : "water" in value ? {
        __kind__: "water",
        water: value.water
    } : "prismScale" in value ? {
        __kind__: "prismScale",
        prismScale: value.prismScale
    } : "lightning" in value ? {
        __kind__: "lightning",
        lightning: value.lightning
    } : "ovalStone" in value ? {
        __kind__: "ovalStone",
        ovalStone: value.ovalStone
    } : "shineStone" in value ? {
        __kind__: "shineStone",
        shineStone: value.shineStone
    } : "seaScale" in value ? {
        __kind__: "seaScale",
        seaScale: value.seaScale
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NinjaTechnique>): Array<NinjaTechnique> {
    return value.map((x)=>from_candid_NinjaTechnique_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Monster>): Array<Monster> {
    return value.map((x)=>from_candid_Monster_n16(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    victories: bigint;
    ninjaName: string;
    avatarUrl?: string;
    dojoSeals: bigint;
    clanName: string;
}): {
    victories: bigint;
    ninjaName: string;
    avatarUrl: [] | [string];
    dojoSeals: bigint;
    clanName: string;
} {
    return {
        victories: value.victories,
        ninjaName: value.ninjaName,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        dojoSeals: value.dojoSeals,
        clanName: value.clanName
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
