/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Blob = Uint8Array;
export type ElementalMastery = { 'ice' : string } |
  { 'magnetizer' : string } |
  { 'magmarizer' : string } |
  { 'dark' : string } |
  { 'dawn' : string } |
  { 'dusk' : string } |
  { 'fire' : string } |
  { 'wind' : string } |
  { 'metalCoat' : string } |
  { 'upgrade' : string } |
  { 'earth' : string } |
  { 'kingRock' : string } |
  { 'skyScale' : string } |
  { 'protector' : string } |
  { 'hydration' : string } |
  { 'moonStone' : string } |
  { 'water' : string } |
  { 'prismScale' : string } |
  { 'lightning' : string } |
  { 'ovalStone' : string } |
  { 'shineStone' : string } |
  { 'seaScale' : string };
export interface Monster {
  'battleTechniques' : Array<NinjaTechnique>,
  'level' : bigint,
  'baseSpeed' : bigint,
  'monsterName' : string,
  'baseAttack' : bigint,
  'masteryElement' : [] | [ElementalMastery],
  'baseDefense' : bigint,
  'images' : Array<MonsterImage>,
}
export interface MonsterImage {
  'isAnimated' : boolean,
  'imagePath' : string,
  'imageUrl' : string,
  'isRawImage' : boolean,
  'image' : Blob,
}
export interface MonsterUltimate {
  'shenanigans' : bigint,
  'speed' : bigint,
  'stage' : string,
  'monsterId' : bigint,
  'defense' : bigint,
  'monsterName' : string,
  'agility' : bigint,
  'attack' : bigint,
  'reactions' : bigint,
  'images' : Array<MonsterImage>,
}
export interface NinjaTechnique {
  'name' : string,
  'effect' : [] | [TechniqueEffect],
  'power' : bigint,
}
export type TechniqueEffect = { 'boostSpeed' : null } |
  { 'paralyzeOpponent' : null } |
  { 'confuseOpponent' : null } |
  { 'boostDefense' : null } |
  { 'boostAttack' : null };
export interface UserProfile {
  'victories' : bigint,
  'ninjaName' : string,
  'avatarUrl' : [] | [string],
  'dojoSeals' : bigint,
  'clanName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDojoSeals' : ActorMethod<[], Array<string>>,
  'getLog' : ActorMethod<[], Array<string>>,
  'getMonsterDXData' : ActorMethod<[string], [] | [Monster]>,
  'getMonsters' : ActorMethod<[], Array<Monster>>,
  'getOpponent' : ActorMethod<[string], string>,
  'getUltimateMonsters' : ActorMethod<[], Array<MonsterUltimate>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];