/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'victories' : IDL.Nat,
  'ninjaName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'dojoSeals' : IDL.Nat,
  'clanName' : IDL.Text,
});
export const TechniqueEffect = IDL.Variant({
  'boostSpeed' : IDL.Null,
  'paralyzeOpponent' : IDL.Null,
  'confuseOpponent' : IDL.Null,
  'boostDefense' : IDL.Null,
  'boostAttack' : IDL.Null,
});
export const NinjaTechnique = IDL.Record({
  'name' : IDL.Text,
  'effect' : IDL.Opt(TechniqueEffect),
  'power' : IDL.Nat,
});
export const ElementalMastery = IDL.Variant({
  'ice' : IDL.Text,
  'magnetizer' : IDL.Text,
  'magmarizer' : IDL.Text,
  'dark' : IDL.Text,
  'dawn' : IDL.Text,
  'dusk' : IDL.Text,
  'fire' : IDL.Text,
  'wind' : IDL.Text,
  'metalCoat' : IDL.Text,
  'upgrade' : IDL.Text,
  'earth' : IDL.Text,
  'kingRock' : IDL.Text,
  'skyScale' : IDL.Text,
  'protector' : IDL.Text,
  'hydration' : IDL.Text,
  'moonStone' : IDL.Text,
  'water' : IDL.Text,
  'prismScale' : IDL.Text,
  'lightning' : IDL.Text,
  'ovalStone' : IDL.Text,
  'shineStone' : IDL.Text,
  'seaScale' : IDL.Text,
});
export const Blob = IDL.Vec(IDL.Nat8);
export const MonsterImage = IDL.Record({
  'isAnimated' : IDL.Bool,
  'imagePath' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isRawImage' : IDL.Bool,
  'image' : Blob,
});
export const Monster = IDL.Record({
  'battleTechniques' : IDL.Vec(NinjaTechnique),
  'level' : IDL.Nat,
  'baseSpeed' : IDL.Nat,
  'monsterName' : IDL.Text,
  'baseAttack' : IDL.Nat,
  'masteryElement' : IDL.Opt(ElementalMastery),
  'baseDefense' : IDL.Nat,
  'images' : IDL.Vec(MonsterImage),
});
export const MonsterUltimate = IDL.Record({
  'shenanigans' : IDL.Nat,
  'speed' : IDL.Nat,
  'stage' : IDL.Text,
  'monsterId' : IDL.Nat,
  'defense' : IDL.Nat,
  'monsterName' : IDL.Text,
  'agility' : IDL.Nat,
  'attack' : IDL.Nat,
  'reactions' : IDL.Nat,
  'images' : IDL.Vec(MonsterImage),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDojoSeals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLog' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMonsterDXData' : IDL.Func([IDL.Text], [IDL.Opt(Monster)], ['query']),
  'getMonsters' : IDL.Func([], [IDL.Vec(Monster)], ['query']),
  'getOpponent' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUltimateMonsters' : IDL.Func([], [IDL.Vec(MonsterUltimate)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'victories' : IDL.Nat,
    'ninjaName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'dojoSeals' : IDL.Nat,
    'clanName' : IDL.Text,
  });
  const TechniqueEffect = IDL.Variant({
    'boostSpeed' : IDL.Null,
    'paralyzeOpponent' : IDL.Null,
    'confuseOpponent' : IDL.Null,
    'boostDefense' : IDL.Null,
    'boostAttack' : IDL.Null,
  });
  const NinjaTechnique = IDL.Record({
    'name' : IDL.Text,
    'effect' : IDL.Opt(TechniqueEffect),
    'power' : IDL.Nat,
  });
  const ElementalMastery = IDL.Variant({
    'ice' : IDL.Text,
    'magnetizer' : IDL.Text,
    'magmarizer' : IDL.Text,
    'dark' : IDL.Text,
    'dawn' : IDL.Text,
    'dusk' : IDL.Text,
    'fire' : IDL.Text,
    'wind' : IDL.Text,
    'metalCoat' : IDL.Text,
    'upgrade' : IDL.Text,
    'earth' : IDL.Text,
    'kingRock' : IDL.Text,
    'skyScale' : IDL.Text,
    'protector' : IDL.Text,
    'hydration' : IDL.Text,
    'moonStone' : IDL.Text,
    'water' : IDL.Text,
    'prismScale' : IDL.Text,
    'lightning' : IDL.Text,
    'ovalStone' : IDL.Text,
    'shineStone' : IDL.Text,
    'seaScale' : IDL.Text,
  });
  const Blob = IDL.Vec(IDL.Nat8);
  const MonsterImage = IDL.Record({
    'isAnimated' : IDL.Bool,
    'imagePath' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isRawImage' : IDL.Bool,
    'image' : Blob,
  });
  const Monster = IDL.Record({
    'battleTechniques' : IDL.Vec(NinjaTechnique),
    'level' : IDL.Nat,
    'baseSpeed' : IDL.Nat,
    'monsterName' : IDL.Text,
    'baseAttack' : IDL.Nat,
    'masteryElement' : IDL.Opt(ElementalMastery),
    'baseDefense' : IDL.Nat,
    'images' : IDL.Vec(MonsterImage),
  });
  const MonsterUltimate = IDL.Record({
    'shenanigans' : IDL.Nat,
    'speed' : IDL.Nat,
    'stage' : IDL.Text,
    'monsterId' : IDL.Nat,
    'defense' : IDL.Nat,
    'monsterName' : IDL.Text,
    'agility' : IDL.Nat,
    'attack' : IDL.Nat,
    'reactions' : IDL.Nat,
    'images' : IDL.Vec(MonsterImage),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDojoSeals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLog' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMonsterDXData' : IDL.Func([IDL.Text], [IDL.Opt(Monster)], ['query']),
    'getMonsters' : IDL.Func([], [IDL.Vec(Monster)], ['query']),
    'getOpponent' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUltimateMonsters' : IDL.Func([], [IDL.Vec(MonsterUltimate)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };